sudo: required
script:
- "./.test/run.sh"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: GhYsMUP8TJbO6VNaZ6XSTEX7KROKVWD4ap/E/SOJoap/8zywUx5aK+2IjGtqH4m2Jo2x4q9e0rEkCpWDqD+pncjYtYDCoc48eloFyZAVeXafugS8sFgb1LmLqVnqyMebpQuSlTde6wMTf3ELM7n1uGE/dV7zAaXSA5oRF/QIcfTlXIeIxAro9fvyPTyshTEzutEieeIuuA8tSpEVOyYRDP5cj+Tb5zLN4OIS5h3hBsLk4XEO1vNx3S9L7RiB9Q8cQmmd5HUTfTEGXwEAnE77pekCGWyIBTeicg9zGRHunbkiExNXXpRyx4gZ7uL2ZIb/AzmmSr+TrBaBAPW0OJEgtTnX2JtVPBKfpxblrjnfbzNmGnW6J21uIJNMORv4wpuBRi2e2WHWuBs+HAYn4Vdnuon6A28v0fQ0H9Uc6KG4ZS1U3aJsSZBXuuftc+ZMjZ02wB6vwqUD/qU8RH9/nJXAX2EiYIZKGl5UJ8KmPyRLHUSA7YI64WT83kXl4rpZJFb00EDWleSY8YiSynN1yuPxUiwm85aJ52B8/tgHhvMY9FeBIOwg1teoeuBg7Wm0xTcivDYNYWIrcD4P6Teb/bFvAh5G9vqLhOcsFv2FPJPd6SL905gz1zoA/XEmDOi15Lgmt2X18czgiytFvUhf44b76IySNfQlsfhX5nOlIFKIoD8=
  - DEFOLD_USER=bjorn.ritzl@king.com
  - DEFOLD_BOOSTRAP_COLLECTION=/test/test.collectionc
